#Client Config
#Wed Jul 08 19:33:54 BST 2026
File_Chooser_Window=
FullScreen=0
Last_directory=data/mekfiles
StartupGui=SPLASH_SCREEN
TabbedWindow=111;71;1952;1120
applicationExitPrompt=true
includeLicense=false
lookAndFeel=com.formdev.flatlaf.FlatDarculaLaf
mekAutoCompact=true
mekAutoSort=true
mekAutofill=true
mulDndBehaviour=0
nag_equipment_ctrlclick=true
nag_import_settings=false
pqAdjustedBV=false
pqDamage=false
pqShowPilotData=true
pqSinglePrint=true
rs_armor_grouping=true
rs_bold_type=true
rs_color=ALL
rs_condensed_reference=false
rs_damage=false
rs_damage_color=\#EE0000
rs_explicit_zero_mod=DASH
rs_extra_physicals=false
rs_fancy_pips=false
rs_font=Dialog
rs_frameless=false
rs_heat_profile=true
rs_heat_scale_marker=ASTERISK
rs_hit_mod=EDGE
rs_intrinsic_physicals=NONE
rs_mek_names=IS_CLAN
rs_merge_identical_equipment=true
rs_paper_size=ISO_A4
rs_progress_bar=true
rs_reference=true
rs_row_shading=true
rs_scale_factor=1
rs_scale_units=HEXES
rs_show_c3bv=true
rs_show_era=true
rs_show_pilot_data=true
rs_show_quirks=true
rs_show_role=true
rs_show_tech_level=false
rs_tac_ops_heat=false
rs_tac_ops_vehicle_effectiveness=false
rs_weapons_order=DEFAULT
skipSafetyPrompts=false
techProgression=false
techShowExtinct=false
techShowFaction=false
techUnofficialNoYear=false
techUseYear=true
techYear=3145
useTROFormat=true
